### PR TITLE
views.py first 70 lines code

### PR DESCRIPTION
**Pull request by Deepthi2001**
website/core/views.py

### CODE REVIEW

**Comment by aditj** [comment]
@Deepthi2001 did you check for any syntactical errors by running the server?

**Comment by Deepthi2001** [comment]
Since it is a half code which is of only 70 lines  I didnt able to check
the code ...

**Comment by aditj** [comment]
I meant specifically for syntactical errors but okay I am accepting this we'll reopen this if there is any problem. Thanks :)

**Comment by Deepthi2001** [comment]
Ya I checked.. No syntax errors. Sent from my Huawei Mobile-------- Original Message --------Subject: Re: [Coding-Club-IITG/e-learning-site] views.py first 70 lines code (#1)From: Adit Jain To: Coding-Club-IITG/e-learning-site CC: Saideepthi ,Mention 
I meant specifically for syntactical errors but okay I am accepting this we'll reopen this if there is any problem. Thanks :)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Coding-Club-IITG/e-learning-site/pull/1#issuecomment-620185894",
"url": "https://github.com/Coding-Club-IITG/e-learning-site/pull/1#issuecomment-620185894",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Pull request merged**
