### PR TITLE
Create urls.py

### PR DESCRIPTION
**Pull request by sribala0104**

### CODE REVIEW

**Comment by aditj** [comment]
Have you tested the site?

**Comment by sweetie0104** [comment]
Won't there be a requirement of the other files even for testing the site? Could you explain me how to test the part assigned to me? I'm little confused 😬

**Comment by sribala0104** [comment]
How to test without the other files? Could you guide me if any? There were no syntactical errors though.

**Comment by aditj** [comment]
@sweetie0104 Yes, you can't test it without the other files. Let's merge all the files and then we'll create another issue for testing.

**Pull request merged**
